layout_spectrum: 0.8046595
typography_spectrum: 0.2222222
color:
  saturation: 0.6149619
  lightness: 0.2360027
  brandStrength: 0.4481353
  rhythmicContrast: 0.3879311
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: 'Rameel Raymundo '
